spring:
  kafka:
    bootstrap-servers: localhost:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: seat-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "co.istad.chan.seatinventoryservice.events"
        spring.json.value.default.type: co.istad.chan.seatinventoryservice.events.BookingCreatedEvent
        spring.json.use.type.headers: false

  application:
    name: seat-inventory-service
  datasource:
    url: jdbc:postgresql://localhost:6168/seatdb
    username: itpusr
    password: itp@168
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
       ddl-auto: update
    show-sql: false
    properties:
        hibernate:
          format_sql: false



server:
  port: 9997
logging:
  level:
    co.istad.chan.seatinventoryservice.listener.SeatInventoryListener: DEBUG
